# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azureprice < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-gitmoji"
  version "0.0.1-rc2"

  on_macos do
    url "https://github.com/muandane/azureprice/releases/download/v0.0.1-rc2/azureprice_0.0.1-rc2_darwin_all.tar.gz"
    sha256 "e86af3d33ac28bc0956eb29ab1044771acc51c0adc6020459d598641fd7f4690"

    def install
      bin.install "azureprice"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/azureprice/releases/download/v0.0.1-rc2/azureprice_0.0.1-rc2_linux_arm64.tar.gz"
      sha256 "4fd5c1d267ce3694df1a3e8e52aa36b4be5692ed947d2dae3904ee352eea80d9"

      def install
        bin.install "azureprice"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muandane/azureprice/releases/download/v0.0.1-rc2/azureprice_0.0.1-rc2_linux_amd64.tar.gz"
      sha256 "5ecd285103d731de4f39d3ed4cbb85280321922ec1bf01907491acb90359323f"

      def install
        bin.install "azureprice"
      end
    end
  end
end
