# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Azureprice < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-gitmoji"
  version "0.0.1-rc1"

  on_macos do
    url "https://github.com/muandane/azureprice/releases/download/v0.0.1-rc1/azureprice_0.0.1-rc1_darwin_all.tar.gz"
    sha256 "463167a370117963490ecdddc7123f1e35c54c1380d86527d217b114f4020b56"

    def install
      bin.install "azureprice"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/muandane/azureprice/releases/download/v0.0.1-rc1/azureprice_0.0.1-rc1_linux_amd64.tar.gz"
      sha256 "a5f2996b46eabd71a81a1dc245bf60f9a59a9da26671289abe42e00cf53e8546"

      def install
        bin.install "azureprice"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/azureprice/releases/download/v0.0.1-rc1/azureprice_0.0.1-rc1_linux_arm64.tar.gz"
      sha256 "5ddb927aaa04d57f5345552e892bc210271ceea6a831a94adaf8c922666dde2b"

      def install
        bin.install "azureprice"
      end
    end
  end
end
