# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChartVersion < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-gitmoji"
  version "0.0.1"

  on_macos do
    url "https://github.com/muandane/chart-version/releases/download/v0.0.1/chart-version_0.0.1_darwin_all.tar.gz"
    sha256 "0fee8af89aa86a401d44a20ae69bbcc4f98fa14e09eeada4b57807a140250feb"

    def install
      bin.install "chart-version"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/chart-version/releases/download/v0.0.1/chart-version_0.0.1_linux_arm64.tar.gz"
      sha256 "55f5f037ae8b65ce55832a935e2f5eb74c64027e249e1126e38e10983cb43d7f"

      def install
        bin.install "chart-version"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muandane/chart-version/releases/download/v0.0.1/chart-version_0.0.1_linux_amd64.tar.gz"
      sha256 "1735ac1389a452dfb039260290077fa58c2751e23129ff06dd97933bcf025fcf"

      def install
        bin.install "chart-version"
      end
    end
  end
end
