# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcost < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-gitmoji"
  version "0.0.1-rc3"

  on_macos do
    url "https://github.com/muandane/cloudcost/releases/download/v0.0.1-rc3/cloudcost_0.0.1-rc3_darwin_all.tar.gz"
    sha256 "50b07ca4177e34969dfd1b5d603719b09cd0f7752dfc1d6cb960202f2c1efe1f"

    def install
      bin.install "cloudcost"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/cloudcost/releases/download/v0.0.1-rc3/cloudcost_0.0.1-rc3_linux_arm64.tar.gz"
      sha256 "33cdff30b6f05a4d10ddc2504f6158bf32b3ef1c3fe0c7b7d3cee68ddd903424"

      def install
        bin.install "cloudcost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muandane/cloudcost/releases/download/v0.0.1-rc3/cloudcost_0.0.1-rc3_linux_amd64.tar.gz"
      sha256 "093a0d0ef03d9d6b5a1113ac8de594a558bdaba531a7707be54484656cf052db"

      def install
        bin.install "cloudcost"
      end
    end
  end
end
