# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcost < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-gitmoji"
  version "0.0.1-rc2-calc"

  on_macos do
    url "https://github.com/muandane/azureprice/releases/download/v0.0.1-rc2-calc/azureprice_0.0.1-rc2-calc_darwin_all.tar.gz"
    sha256 "cd3ab3d5dea92a76a0a7456f30f2ac4af403d0c3e95f220d8d97cd0d8f623dd8"

    def install
      bin.install "azureprice"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/azureprice/releases/download/v0.0.1-rc2-calc/azureprice_0.0.1-rc2-calc_linux_arm64.tar.gz"
      sha256 "0e0a6323f87458b54e9f6b453190794e8c80d545ed1ad8e9cfaf90f4e9f6907d"

      def install
        bin.install "cloudcost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muandane/azureprice/releases/download/v0.0.1-rc2-calc/azureprice_0.0.1-rc2-calc_linux_amd64.tar.gz"
      sha256 "0d5cce8999f811848cfdc54bff755ee6cea04ce1fbf995f784aea6d673eed6f7"

      def install
        bin.install "cloudcost"
      end
    end
  end
end
