# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goji < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-gitmoji"
  version "0.0.1-rc6"

  on_macos do
    url "https://github.com/muandane/goji/releases/download/v0.0.1-rc6/goji_0.0.1-rc6_darwin_all.tar.gz"
    sha256 "721380c35a281ef8261b967fc05a396b4cb3336c51ee13e2cc2ec431246a8855"

    def install
      bin.install "goji"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/goji/releases/download/v0.0.1-rc6/goji_0.0.1-rc6_linux_arm64.tar.gz"
      sha256 "20a884ce3764801eea56a901336f33a619e0828ce69c8ecf19649a6ded8fe396"

      def install
        bin.install "goji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muandane/goji/releases/download/v0.0.1-rc6/goji_0.0.1-rc6_linux_amd64.tar.gz"
      sha256 "70453addee88c3d466b515adcedc71efbc0287bc7594b56db58e514fdbee2f81"

      def install
        bin.install "goji"
      end
    end
  end
end
