# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goji < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-gitmoji"
  version "0.0.1-rc3"

  on_macos do
    url "https://github.com/muandane/goji/releases/download/v0.0.1-rc3/goji_0.0.1-rc3_darwin_all.tar.gz"
    sha256 "4a662bc4ec0e21096a54aade1fb46f76d8ad2003cf78c2125fecd6d56ac1c9f7"

    def install
      bin.install "goji"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/goji/releases/download/v0.0.1-rc3/goji_0.0.1-rc3_linux_arm64.tar.gz"
      sha256 "245e8ceae2b517a0a7de1554e98b713c338b04b7d3a717871570c2bc5f8ea6b4"

      def install
        bin.install "goji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muandane/goji/releases/download/v0.0.1-rc3/goji_0.0.1-rc3_linux_amd64.tar.gz"
      sha256 "b1b1b252b88e49eb8c8e888bf9ffcb1a1b27635ec99e1b170eb0e852cdb75ac3"

      def install
        bin.install "goji"
      end
    end
  end
end
