# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goji < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-goji"
  version "0.0.1-rc1"

  on_macos do
    url "https://github.com/muandane/goji/releases/download/v0.0.1-rc1/goji_0.0.1-rc1_darwin_all.tar.gz"
    sha256 "715b53a6874e47c64d5de1587c2d29b13cd9ee86dc1168a52ba1cdfab0828b47"

    def install
      bin.install "goji"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/goji/releases/download/v0.0.1-rc1/goji_0.0.1-rc1_linux_arm64.tar.gz"
      sha256 "bebaed372f3f3c65cebc071dfab893c1893b9ee213390ad6a8bd8bfc1530f4d2"

      def install
        bin.install "goji"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muandane/goji/releases/download/v0.0.1-rc1/goji_0.0.1-rc1_linux_amd64.tar.gz"
      sha256 "5d7e96d3cbf6d70ecb446db9a635025aaf6cec12d0cb262f0057b046463472f7"

      def install
        bin.install "goji"
      end
    end
  end
end
