# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goji < Formula
  desc ""
  homepage "https://github.com/muandane/homebrew-gitmoji"
  version "0.0.1-rc8"

  depends_on "git"

  on_macos do
    url "https://github.com/muandane/goji/releases/download/v0.0.1-rc8/goji_Darwin_all.tar.gz"
    sha256 "923dce3fb3ccc28282c89cbbe9cb4ca403cb729ed18ab9994c87d8c7f8ba62b8"

    def install
      bin.install "goji"
      bash_completion.install "completions/goji.bash" => "goji"
      zsh_completion.install "completions/goji.zsh" => "_goji"
      fish_completion.install "completions/goji.fish"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/muandane/goji/releases/download/v0.0.1-rc8/goji_Linux_arm64.tar.gz"
      sha256 "e7816ce1b031ca8ebbce2df09e964de42404b36f1afb6abdfc546b25780cf7b1"

      def install
        bin.install "goji"
        bash_completion.install "completions/goji.bash" => "goji"
        zsh_completion.install "completions/goji.zsh" => "_goji"
        fish_completion.install "completions/goji.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/muandane/goji/releases/download/v0.0.1-rc8/goji_Linux_x86_64.tar.gz"
      sha256 "c224a728c732db9b5532733690e7df4314baa231ad9ef621635fd07fcd87c616"

      def install
        bin.install "goji"
        bash_completion.install "completions/goji.bash" => "goji"
        zsh_completion.install "completions/goji.zsh" => "_goji"
        fish_completion.install "completions/goji.fish"
      end
    end
  end
end
